### ISSUE TITLE
Extract All Does Nothing with .pck files

### ISSUE THREAD

**Issue by jredfox** [jam1garner/WiiUZip#5]
Version: Latest
I imported mincraft texture pack x16.pck and then it just does nothing. I am looking for a proper pck extractor but, your's doesn't work. I was hoping you would fix this if it's still active

**Comment by jam1garner** [comment]
Go look around for "PCK Editor" or something like that, it's basically a repost of my (seperate) editor for Minecraft PCK files

**Comment by jredfox** [comment]
Could you link me to it your program said it could extract .pck files but it didn't. Please I need help
